#!/bin/sh

#__________________________________________________________________________________________#
#                                                                                          #
# ** ALCE (Audio Live Coding Environment) **                                               #
# Questo script serve a scaricare ed installare i pacchetti di sistema,                    #
# i sorgenti software e le dipendenze necessarie al sistema per configurare                #
# l'ambiente di sviluppo audio interattivo 'ALCE' per shell/bash                           #
# che utilizza software open source quali: Jackd come demone audio,                        #
# l'editor a linea di comando Jed,                                                         #
# gli ambienti di sviluppo integrati sonic-pi e supercollider per la sintesi audio,        #
# Rust e Ruby per il controllo dei dati.                                                   #
# Nestore Locarno. Donazioni Bitcoin: 3NWbGmuLo7uoA8tiZG329X3i2W4d65oUUK                   #
# >> Snippet Repository:                                                                   #
# Ghostbin idx: 98z4d                                                                      #
# Pastebin.com idx: DAUgW8xx                                                               #
# PasteFs.com idx: pid/114820                                                              #
# Paste.Ubuntu.com idx: p/h8cZxYTjy7                                                       #
# CodePad.org idx: Ly9gYWKC                                                                #
# TagMyCode.com idx: snippet/12170/alce                                                    #
# Cacher.io idx: snippet/fd7af875c04233183321                                              #
# Paste4BTC.com idx: FDJECUaW                                                              #
#                                                                                          #
#__________________________________________________________________________________________#

#SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Installazione pacchetti sistema base..."
sudo apt install -y git build-essential buildapp software-properties-common
echo "Installazione moduli audio..."
sudo apt install -y jack pulseaudo pulseaudio-module-jack
echo "Installazione componenti software base..."
sudo apt install -y mc gem jed curl
echo "Installazione server audio e synth..."
sudo apt install -y sonic-pi
echo "Installazione dipendenze completata!"
echo "Chiusura processi in corso..."
echo "ATTENZIONE!! Necessario riavvio del sistema!" 
echo "Salvataggio progeressi installazione in corso..."
echo "sudo gem install sonic-pi-cli" > resume.setup
echo "curl https://sh.rustup.rs -sSf | sh" >> resume.setup
echo "source $HOME/.cargo/env" >> resume.setup
echo "cargo install --git https://github.com/lpil/sonic-pi-tool/ --force" >> resume.setup
echo 'echo "Creazione file di configurazione e avvio in corso..."' >> resume.setup
echo "sudo git clone https://github.com/samaaron/sonic-pi" >> resume.setup
echo 'sudo cp $HOME/alce/buffer0.rb $HOME/sonic-pi/buffer.rb' >> resume.setup
echo 'echo "cd sonic-pi; pasuspender -- jackd -r -d alsa -d hw:0,0 & sleep 2" > start-alce' >> resume.setup 
echo 'echo "sonic-pi-tool start-server & sleep 2; jed buffer.rb" >> start-alce' >> resume.setup
echo 'sudo chmod +x start-alce' >> resume.setup
echo 'sudo chmod +777 sonic-pi/' >> resume.setup
echo 'echo "sonic-pi-tool logs" > sonic-pi/alce-log' >> resume.setup
echo 'sudo chmod +x sonic-pi/alce-log' >> resume.setup 
echo 'echo "cat buffer.rb | sonic_pi" > sonic-pi/P' >> resume.setup
echo 'sudo chmod +x sonic-pi/P' >> resume.setup
echo 'echo "sonic_pi stop" > sonic-pi/S' >> resume.setup
echo 'sudo chmod +x sonic-pi/S' >> resume.setup
echo 'sudo chmod +777 sonic-pi/buffer.rb' >> resume.setup
sudo chmod +x resume.setup
sudo usermod -a -G audio $USER
echo "RIAVVIO DEL SISTEMA IMPOSTATO! 10 secondi."
echo "A riavvio completato digitare il comando './resume.setup'" & sleep 10
reboot

